

INSERT INTO LFINTEGRATION.XXLF_SHOPIFY_EBS_ACCNTS_IMP_STG (

  G_ID, LFINTG_EXECUTION_ID, ORACLE_STATUS, ORACLE_MESSAGE, OIC_STATUS, OIC_MESSAGE,

  OIC_COMPANY_NAME, OIC_NAME, OIC_CUSTOMER_LOCATION_NAME,

  OIC_BILLING_STREET, OIC_BILLING_CITY, OIC_BILLING_POSTALCODE, OIC_BILLING_STATE, OIC_BILLING_COUNTY, OIC_BILLING_COUNTRY,

  OIC_SHIPPING_STREET, OIC_SHIPPING_CITY, OIC_SHIPPING_POSTALCODE, OIC_SHIPPING_STATE, OIC_SHIPPING_COUNTY, OIC_SHIPPING_COUNTRY,

  OIC_FIRST_NAME, OIC_LAST_NAME, OIC_PHONE, OIC_EMAIL,

  OIC_SALES_CHANNEL_LOOKUP, OIC_SCIFIT_DEALER_FLAG, OIC_DEALER_END_CUSTOMER, OIC_BILLTO_LOCATION_ID

) VALUES (

  'TEST18',

  143410,

  'NEW', NULL, NULL, NULL,

  'LF test 4','','BETHESDA MARRIOTT',

  '5151 POOKS HILL RD','BETHESDA','20814-5423','MD',NULL,'US',

  '5151 POOKS HILL RD','BETHESDA','20814-5423','MD',NULL,'US',

  '','', '','',

  'MARRIOTT', '', 'true', '415228-1835961-889779-921474' 

);
 